/*
 * Copyright 2018 EMBL - European Bioinformatics Institute
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.ac.ebi.eva.accession.release.configuration;

public class BeanNames {

    public static final String ACTIVE_ACCESSION_RELEASE_EVA_FLOW = "ACTIVE_ACCESSION_RELEASE_EVA_FLOW";

    public static final String ACTIVE_ACCESSION_RELEASE_DBSNP_FLOW = "ACTIVE_ACCESSION_RELEASE_DBSNP_FLOW";

    public static final String MERGED_ACCESSION_RELEASE_EVA_FLOW = "MERGED_ACCESSION_RELEASE_EVA_FLOW";

    public static final String MERGED_ACCESSION_RELEASE_DBSNP_FLOW = "MERGED_ACCESSION_RELEASE_DBSNP_FLOW";

    public static final String DEPRECATED_ACCESSION_RELEASE_EVA_FLOW = "DEPRECATED_ACCESSION_RELEASE_EVA_FLOW";

    public static final String DEPRECATED_ACCESSION_RELEASE_DBSNP_FLOW = "DEPRECATED_ACCESSION_RELEASE_DBSNP_FLOW";

    public static final String MERGED_DEPRECATED_ACCESSION_RELEASE_EVA_FLOW = "MERGED_DEPRECATED_ACCESSION_RELEASE_EVA_FLOW";

    public static final String MERGED_DEPRECATED_ACCESSION_RELEASE_DBSNP_FLOW = "MERGED_DEPRECATED_ACCESSION_RELEASE_DBSNP_FLOW";

    // common beans
    public static final String ACTIVE_ACCESSION_RELEASE_JOB = "ACTIVE_ACCESSION_RELEASE_JOB";

    public static final String MERGED_ACCESSION_RELEASE_JOB = "MERGED_ACCESSION_RELEASE_JOB";

    public static final String DEPRECATED_ACCESSION_RELEASE_JOB = "DEPRECATED_ACCESSION_RELEASE_JOB";

    public static final String MERGED_DEPRECATED_ACCESSION_RELEASE_JOB = "MERGED_DEPRECATED_ACCESSION_RELEASE_JOB";

    public static final String ACCESSION_RELEASE_JOB = "ACCESSION_RELEASE_JOB";

    public static final String CREATE_INCREMENTAL_ACCESSION_RELEASE_JOB = "CREATE_INCREMENTAL_ACCESSION_RELEASE_JOB";

    public static final String RELEASE_PROCESSOR = "RELEASE_PROCESSOR";

    public static final String INCREMENTAL_RELEASE_WRITER = "INCREMENTAL_RELEASE_WRITER";

    public static final String EXCLUDE_VARIANTS_LISTENER = "EXCLUDE_VARIANTS_LISTENER";

    public static final String PROGRESS_LISTENER = "PROGRESS_LISTENER";

    // dbsnp beans
    public static final String DBSNP_FLOW = "DBSNP_FLOW";

    public static final String CREATE_INCREMENTAL_ACCESSION_RELEASE_STEP = "CREATE_INCREMENTAL_ACCESSION_RELEASE_STEP";

    public static final String RELEASE_DBSNP_MAPPED_ACTIVE_VARIANTS_STEP = "RELEASE_DBSNP_MAPPED_ACTIVE_VARIANTS_STEP";

    public static final String RELEASE_DBSNP_MAPPED_MERGED_VARIANTS_STEP = "RELEASE_DBSNP_MAPPED_MERGED_VARIANTS_STEP";

    public static final String RELEASE_DBSNP_MAPPED_MERGED_DEPRECATED_VARIANTS_STEP =
            "RELEASE_DBSNP_MAPPED_MERGED_DEPRECATED_VARIANTS_STEP";

    public static final String RELEASE_DBSNP_MULTIMAP_VARIANTS_STEP = "RELEASE_DBSNP_MULTIMAP_VARIANTS_STEP";

    public static final String RELEASE_DBSNP_MAPPED_DEPRECATED_VARIANTS_STEP =
            "RELEASE_DBSNP_MAPPED_DEPRECATED_VARIANTS_STEP";

    public static final String DBSNP_ACCESSIONED_VARIANT_READER = "DBSNP_ACCESSIONED_VARIANT_READER";

    public static final String DBSNP_MERGED_VARIANT_READER = "DBSNP_MERGED_VARIANT_READER";

    public static final String DBSNP_DEPRECATED_VARIANT_READER = "DBSNP_DEPRECATED_VARIANT_READER";

    public static final String DBSNP_MERGED_DEPRECATED_VARIANT_READER = "DBSNP_MERGED_DEPRECATED_VARIANT_READER";

    public static final String DBSNP_MULTIMAP_VARIANT_READER = "DBSNP_MULTIMAP_VARIANT_READER";

    public static final String DBSNP_RELEASE_WRITER = "DBSNP_RELEASE_WRITER";

    public static final String DBSNP_MERGED_RELEASE_WRITER = "DBSNP_MERGED_RELEASE_WRITER";

    public static final String DBSNP_MULTIMAP_RELEASE_WRITER = "DBSNP_MULTIMAP_RELEASE_WRITER";

    public static final String DBSNP_MERGED_DEPRECATED_RELEASE_WRITER = "DBSNP_MERGED_DEPRECATED_RELEASE_WRITER";

    public static final String DBSNP_DEPRECATED_RELEASE_WRITER = "DBSNP_DEPRECATED_RELEASE_WRITER";

    public static final String LIST_DBSNP_ACTIVE_CONTIGS_STEP = "LIST_DBSNP_ACTIVE_CONTIGS_STEP";

    public static final String LIST_DBSNP_MERGED_CONTIGS_STEP = "LIST_DBSNP_MERGED_CONTIGS_STEP";

    public static final String LIST_DBSNP_MULTIMAP_CONTIGS_STEP = "LIST_DBSNP_MULTIMAP_CONTIGS_STEP";

    public static final String DBSNP_ACTIVE_CONTIG_READER = "DBSNP_ACTIVE_CONTIG_READER";

    public static final String DBSNP_MERGED_CONTIG_READER = "DBSNP_MERGED_CONTIG_READER";

    public static final String DBSNP_MULTIMAP_CONTIG_READER = "DBSNP_MULTIMAP_CONTIG_READER";

    public static final String DBSNP_ACTIVE_CONTIG_WRITER = "DBSNP_ACTIVE_CONTIG_WRITER";

    public static final String DBSNP_MERGED_CONTIG_WRITER = "DBSNP_MERGED_CONTIG_WRITER";

    public static final String DBSNP_MULTIMAP_CONTIG_WRITER = "DBSNP_MULTIMAP_CONTIG_WRITER";

    // eva beans
    public static final String EVA_FLOW = "EVA_FLOW";

    public static final String RELEASE_EVA_MAPPED_ACTIVE_VARIANTS_STEP = "RELEASE_EVA_MAPPED_ACTIVE_VARIANTS_STEP";

    public static final String RELEASE_EVA_MAPPED_MERGED_VARIANTS_STEP = "RELEASE_EVA_MAPPED_MERGED_VARIANTS_STEP";

    public static final String RELEASE_EVA_MAPPED_MERGED_DEPRECATED_VARIANTS_STEP =
            "RELEASE_EVA_MAPPED_MERGED_DEPRECATED_VARIANTS_STEP";

    public static final String RELEASE_EVA_MULTIMAP_VARIANTS_STEP = "RELEASE_EVA_MULTIMAP_VARIANTS_STEP";

    public static final String RELEASE_EVA_MAPPED_DEPRECATED_VARIANTS_STEP =
            "RELEASE_EVA_MAPPED_DEPRECATED_VARIANTS_STEP";

    public static final String EVA_ACCESSIONED_VARIANT_READER = "EVA_ACCESSIONED_VARIANT_READER";

    public static final String EVA_MERGED_VARIANT_READER = "EVA_MERGED_VARIANT_READER";

    public static final String EVA_DEPRECATED_VARIANT_READER = "EVA_DEPRECATED_VARIANT_READER";

    public static final String EVA_MERGED_DEPRECATED_VARIANT_READER = "EVA_MERGED_DEPRECATED_VARIANT_READER";

    public static final String EVA_MULTIMAP_VARIANT_READER = "EVA_MULTIMAP_VARIANT_READER";

    public static final String EVA_RELEASE_WRITER = "EVA_RELEASE_WRITER";

    public static final String EVA_MERGED_RELEASE_WRITER = "EVA_MERGED_RELEASE_WRITER";

    public static final String EVA_MULTIMAP_RELEASE_WRITER = "EVA_MULTIMAP_RELEASE_WRITER";

    public static final String EVA_MERGED_DEPRECATED_RELEASE_WRITER = "EVA_MERGED_DEPRECATED_RELEASE_WRITER";

    public static final String EVA_DEPRECATED_RELEASE_WRITER = "EVA_DEPRECATED_RELEASE_WRITER";

    public static final String LIST_EVA_ACTIVE_CONTIGS_STEP = "LIST_EVA_ACTIVE_CONTIGS_STEP";

    public static final String LIST_EVA_MERGED_CONTIGS_STEP = "LIST_EVA_MERGED_CONTIGS_STEP";

    public static final String LIST_EVA_MULTIMAP_CONTIGS_STEP = "LIST_EVA_MULTIMAP_CONTIGS_STEP";

    public static final String EVA_ACTIVE_CONTIG_READER = "EVA_ACTIVE_CONTIG_READER";

    public static final String EVA_MERGED_CONTIG_READER = "EVA_MERGED_CONTIG_READER";

    public static final String EVA_MULTIMAP_CONTIG_READER = "EVA_MULTIMAP_CONTIG_READER";

    public static final String EVA_ACTIVE_CONTIG_WRITER = "EVA_ACTIVE_CONTIG_WRITER";

    public static final String EVA_MERGED_CONTIG_WRITER = "EVA_MERGED_CONTIG_WRITER";

    public static final String EVA_MULTIMAP_CONTIG_WRITER = "EVA_MULTIMAP_CONTIG_WRITER";

    public static final String DUMP_ACTIVE_ACCESSIONS_JOB = "DUMP_ACTIVE_ACCESSIONS_JOB";

    public static final String DUMP_ACTIVE_ACCESSIONS_STEP = "DUMP_ACTIVE_ACCESSIONS_STEP";

    public static final String DUMP_MERGED_ACCESSIONS_JOB = "DUMP_MERGED_ACCESSIONS_JOB";

    public static final String DUMP_MERGED_ACCESSIONS_STEP = "DUMP_MERGED_ACCESSIONS_STEP";

    public static final String DUMP_DEPRECATED_ACCESSIONS_JOB = "DUMP_DEPRECATED_ACCESSIONS_JOB";

    public static final String DUMP_DEPRECATED_ACCESSIONS_STEP = "DUMP_DEPRECATED_ACCESSIONS_STEP";

    public static final String DUMP_RS_ACCESSIONS_IN_FILE = "DUMP_RS_ACCESSIONS_IN_FILE";

    public static final String ACTIVE_ACCESSIONS_RELEASE_FROM_DB_JOB = "ACTIVE_ACCESSIONS_RELEASE_FROM_DB_JOB";

    public static final String ACTIVE_ACCESSIONS_RELEASE_FROM_DB_STEP = "ACTIVE_ACCESSIONS_RELEASE_FROM_DB_STEP";

    public static final String ACTIVE_ACCESSIONS_VARIANT_READER = "ACTIVE_ACCESSIONS_VARIANT_READER";

    public static final String MERGED_ACCESSIONS_RELEASE_FROM_DB_JOB = "MERGED_ACCESSIONS_RELEASE_FROM_DB_JOB";

    public static final String MERGED_ACCESSIONS_RELEASE_FROM_DB_STEP = "MERGED_ACCESSIONS_RELEASE_FROM_DB_STEP";

    public static final String MERGED_ACCESSIONS_VARIANT_READER = "MERGED_ACCESSIONS_VARIANT_READER";

    public static final String DEPRECATED_ACCESSIONS_RELEASE_FROM_DB_JOB = "DEPRECATED_ACCESSIONS_RELEASE_FROM_DB_JOB";

    public static final String DEPRECATED_ACCESSIONS_RELEASE_FROM_DB_STEP = "DEPRECATED_ACCESSIONS_RELEASE_FROM_DB_STEP";

    public static final String DEPRECATED_ACCESSIONS_VARIANT_READER = "DEPRECATED_ACCESSIONS_VARIANT_READER";

}
